### PR TITLE
optimize coconut spawn ABM

### PR DESCRIPTION
**Pull request by Niklp09**
simple performance improvement

### CODE REVIEW

**Comment by wsor4035** [comment]
this comes at the cost of tuning down the fruit

**Comment by Niklp09** [comment]
> this comes at the cost of tuning down the fruit

And why? Can you tell me what I've not considered?

**Comment by SwissalpS** [comment]
hmm, do I understand this correctly? When a palm tree grows it places some trunks of type "moretrees:palm_fruit_trunk_gen" and then the ABM detects these and turns them into normal fruit trunks with coconut(s) around it?
So wouldn't increasing the interval by a factor of 6 make this process slower?

**Comment by SwissalpS** [comment]
on line 48 the abm starts that spawns consecutive coconuts. (and I think it is slow but I'm OK with it)

**Comment by Niklp09** [comment]
The time of execution is only changed, the end result remains the same

**Comment by SwissalpS** [comment]
I'm OK with this PR, the initial coconuts take a little longer to appear giving the CPU a 'breather'

**Review by wsor4035 — APPROVED** [review]

**Pull request merged**
